name: jessie
version: 0.0.0+dev.1
description: JSONPath for Dart
homepage: "https://github.com/f3ath/jessie"

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.9.0

environment:
  sdk: ">=2.8.0 <3.0.0"
